-- Allows the historical RLS migrations to run on a fresh database.
-- Existing installations keep their legacy table and data unchanged.
create table if not exists public.evaluations (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  subject text,
  future_axis integer,
  power_axis integer,
  resilience_score integer,
  current_quadrant integer,
  desired_quadrant integer
);
